---
# Template configuration files for ati

- name: template is copied
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ ati_templates_copy }}"
  when: ati_copy_templates
